### ISSUE TITLE
Issue with submission

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/hw-03-shashwatsinghds#1]
Hi shashwatsinghds, 

I cannot reproduce your submission because you used a local path to read in the data. Please replace these paths with the absolute path in the repo. I suggest using the here() package. See [Project Relative Paths](https://cran.r-project.org/web/packages/here/vignettes/here.html)

**Comment by shashwatsinghds** [comment]
Used here() package to dynamically get the path of the csv file
